#!/bin/sh

SELF=$(cd $(dirname $0); pwd)

function _post() {
    echo ">> create new post"
    if [ $# -eq 0 ]; then
        echo 'you need post name'
        exit 1
    fi
    docker run -v ${SELF}/../:/site --rm -it nutsllc/toybox-hugo hugo new ${1}
}

_post $@ && {
    echo "complete!"
}

exit 0;
